# Generated by Django 4.1.7 on 2023-04-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
