# Generated by Django 4.2 on 2023-04-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0003_delivpart_finmanager_invman_uom_vendor_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='agentimage',
            field=models.ImageField(null=True, upload_to='uploads/customers/'),
        ),
    ]
