# Generated by Django 4.2 on 2023-04-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0004_customer_agentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='agentimage',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Koregaon', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='firstname',
            field=models.CharField(default='Kartik', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default='Singhania', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='pin',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='karsingh@gmail.com', max_length=50),
        ),
    ]
