# Generated by Django 4.2 on 2023-04-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0005_rename_phone_customer_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivpart',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='finmanager',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='invman',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='delivpart',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='delivpart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='delivpart',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='finmanager',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='finmanager',
            name='image',
        ),
        migrations.RemoveField(
            model_name='finmanager',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='invman',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='invman',
            name='image',
        ),
        migrations.RemoveField(
            model_name='invman',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='delivpart',
            name='firstname',
            field=models.CharField(default='Kartik', max_length=50),
        ),
        migrations.AddField(
            model_name='delivpart',
            name='lastname',
            field=models.CharField(default='Singhania', max_length=50),
        ),
        migrations.AddField(
            model_name='finmanager',
            name='firstname',
            field=models.CharField(default='Kartik', max_length=50),
        ),
        migrations.AddField(
            model_name='finmanager',
            name='lastname',
            field=models.CharField(default='Singhania', max_length=50),
        ),
        migrations.AddField(
            model_name='invman',
            name='firstname',
            field=models.CharField(default='Kartik', max_length=50),
        ),
        migrations.AddField(
            model_name='invman',
            name='lastname',
            field=models.CharField(default='Singhania', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='firstname',
            field=models.CharField(default='Kartik', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='lastname',
            field=models.CharField(default='Singhania', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivpart',
            name='city',
            field=models.CharField(default='Koregaon', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivpart',
            name='email',
            field=models.EmailField(default='karsingh@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivpart',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finmanager',
            name='city',
            field=models.CharField(default='Koregaon', max_length=50),
        ),
        migrations.AlterField(
            model_name='finmanager',
            name='email',
            field=models.EmailField(default='karsingh@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='finmanager',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invman',
            name='city',
            field=models.CharField(default='Koregaon', max_length=50),
        ),
        migrations.AlterField(
            model_name='invman',
            name='email',
            field=models.EmailField(default='karsingh@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='invman',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(default='Koregaon', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(default='karsingh@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
