# Generated by Django 4.2 on 2023-04-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0006_rename_phone_delivpart_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='subcategory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(default='fruits', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='color',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
