# Generated by Django 4.2 on 2023-04-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0008_alter_brand_bname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='vendors',
        ),
    ]
